// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOz1dr6B9ulcxf7a0GMwH8VqMVIeoZrNg',
    appId: '1:968313729320:web:7ac66118af9516deb7e01d',
    messagingSenderId: '968313729320',
    projectId: 'chatmandu-1739b',
    authDomain: 'chatmandu-1739b.firebaseapp.com',
    storageBucket: 'chatmandu-1739b.appspot.com',
    measurementId: 'G-ZKE5DPLYGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt2PRR10pKCGxbx_wvE9-mC8QS2kqXGFY',
    appId: '1:968313729320:android:db0d2efdc0bc4413b7e01d',
    messagingSenderId: '968313729320',
    projectId: 'chatmandu-1739b',
    storageBucket: 'chatmandu-1739b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf76fBonR1Db9tMnLQvEGCUIuvvLsCjeY',
    appId: '1:968313729320:ios:cad77b6879c4297fb7e01d',
    messagingSenderId: '968313729320',
    projectId: 'chatmandu-1739b',
    storageBucket: 'chatmandu-1739b.appspot.com',
    iosClientId: '968313729320-ru2tnrl8oa000qaifkladcgd3eebv7lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatmanduu',
  );
}
